export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const CREATE_NEW_RECORD = 'CREATE_NEW_RECORD';
export const DECREASE_ACCOUNT_BALANCE = 'DECREASE_ACCOUNT_BALANCE';
